---
version: "2.1"

services:
  # Database
  db:
    build: ./Database
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./Database/DbScript.sh:/docker-entrypoint-initdb.d/init-database.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trimaniadb
      MYSQL_USER: trilogo
      MYSQL_PASSWORD: 1234
  # Backend
  backend:
    build: ./
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 80:5044
volumes:
  db-data:
