FROM mcr.microsoft.com/dotnet/sdk:6.0 AS BUILD_STAGE
WORKDIR /Backend
COPY *.csproj ./
RUN dotnet restore
COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /Backend
COPY --from=BUILD_STAGE /Backend/out .
EXPOSE 5044
ENV ASPNETCORE_URLS=http://+:5044
ENV ASPNETCORE_ENVIRONMENT = Production
ENTRYPOINT ["dotnet", "Backend.dll"]